name: Build, Scan & Push Docker Image on Release

on:
  release:
    types: [published]
  schedule:
    - cron: "0 3 * * *" # Tous les jours à 03h00 UTC
  workflow_dispatch:       # permet de lancer manuellement aussi
        
jobs:
  call-central:
    uses: veka-server/github-actions-templates/.github/workflows/docker-build.yml@main
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
